### ISSUE TITLE
Some versions of `requests` have a Response object that can't be deepcopy

### ISSUE THREAD

**Issue by hansmosh** [nio-blocks/http_requests#22]
The Response object is placed on the signal as `_resp`. In requests version 2.2.1 (but not in 2.7.0... not sure about in between) this object does not work with `deepcopy`. What this means is that the output signal from HttpRequests blocks can not be sent to two blocks using the clone_signals option of the block router (which is default).

Possible fixes :
- Make including the Response object be optional.
- Warn if the object Response object is not serializable and/or deepcopyable.
- Do nothing in the block, but update the nio block router to handle this better.

**Comment by mattdodge** [comment]
I vote option 3, if a signal can't be deep copied we need to figure that out and not try. Maybe log a warning about it if the block was configured to do so

**Comment by dorzel** [comment]
This was resolved in the router
